services:
  postgres:
    container_name: postgres_db
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=myshopdb'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=jack'
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db
    restart: unless-stopped

  backend:
    container_name: shop_backend
    depends_on:
      - postgres
    build:
      dockerfile: Dockerfile
    ports:
      - "8090:8080"
    networks:
      - db
    environment:
      spring.datasource.url: jdbc:postgresql://postgres_db:5432/myshopdb
      spring.datasource.username: jack
      spring.datasource.password: password
    restart: unless-stopped
volumes:
  db:
networks:
  db:
